trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: "SECURE_TOKENS"
- name: snyk_token
  value: $[variables.SNYKTOKEN]

steps:
- script: | 
     SNYK_TOKEN=$(snyk_token)
     export SNYK_TOKEN
     npm install && npm run client-install
     curl --compressed https://downloads.snyk.io/cli/stable/snyk-linux -o snyk
     chmod +x ./snyk
     mv ./snyk /usr/local/bin/
     npm install snyk-to-html -g
     mkdir -p results
     snyk auth $(SNYK_TOKEN)
     snyk test --all-projects --json-file-output=resutls/oss.json
     ContinueOnError: true
     snyk-to-html -o results/oss.html < results/oss.json
  env:
    SNYK_TOKEN: $(SNYK_TOKEN)
  displayName: "Integrate SCA using Snyk in ADO"
  
- publish: $(System.DefaultWorkingDirectory)/results
  artifact: results
