name: Security Scan

on:
  push:
    branches: main
  workflow_dispatch:  # Allow manual triggers
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

     # - name: Setup Node.js
      #  uses: actions/setup-node@v4
       # with:
        #  node-version: '20'
         # cache: 'npm'

     # - name: Install Dependencies
      #  run: npm ci

      # Run Snyk to check for code vulnerabilities and generate report
      - name: Snyk Code Test
        uses: snyk/actions/node@master
        continue-on-error: true  # Don't fail the workflow on vulnerabilities
        with:
          command: code test
          args: --all-projects --json-file-output=snyk-code.json --sarif-file-output=snyk-code.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ORG: ${{ secrets.SNYK_ORG }}

      # Run Snyk to check for dependencies vulnerabilities and generate report
      - name: Snyk Dependencies Test
        uses: snyk/actions/node@master
        continue-on-error: true  # Don't fail the workflow on vulnerabilities
        with:
          command: test
          args: --all-projects --json-file-output=snyk-deps.json --sarif-file-output=snyk-deps.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ORG: ${{ secrets.SNYK_ORG }}


      # Monitor the project in Snyk
      - name: Monitor Project in Snyk
        uses: snyk/actions/node@master
        with:
          command: monitor
          args: --project-name=github/${{ github.repository }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ORG: ${{ secrets.SNYK_ORG }}



     
